### ISSUE TITLE
cannot run success

### ISSUE THREAD

**Issue by chiangandy** [udger/udger-python#5]
after I install package... sudo pip3 install udger

and running code...
```
from pprint import pprint
from udger import Udger

udger = Udger()

result = udger.parse_ua("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36")
```
I got following error...

Traceback (most recent call last):
  File "test_ua.py", line 6, in <module>
    result = udger.parse_ua("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36")
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/udger/parser.py", line 14, in parse_ua
    ua, class_id, client_id = self._client_detector(ua_string)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/udger/parser.py", line 87, in _client_detector
    ua = self.db_get_first_row(Queries.crawler_sql, ua_string)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/udger/base.py", line 214, in db_get_first_row
    self.db_cursor.execute(sql, params)
sqlite3.OperationalError: no such table: udger_crawler_list

I have no idea how to solve this....please guide me.

**Comment by mallat** [comment]
I assume you don't have a data file ... see https://github.com/udger/udger-python#data-directory

**Comment by chiangandy** [comment]
iI see we can download data file from web site if I buy the commercial license.  How about community edition? can we download for free?

**Comment by mallat** [comment]
This is a paid product. There is no free version.
